package asc

func singleLinkageRows(data ResourceData) ([]string, [][]string) {
	return linkagesRows(&LinkagesResponse{Data: []ResourceData{data}})
}

func registerSingleLinkageRows[T any](extract func(*T) ResourceData) {
	registerRows(func(v *T) ([]string, [][]string) {
		return singleLinkageRows(extract(v))
	})
}

func registerIDStateRows[T any](extract func(*T) (string, string), rows func(string, string) ([]string, [][]string)) {
	registerRows(func(v *T) ([]string, [][]string) {
		id, state := extract(v)
		return rows(id, state)
	})
}

func registerIDBoolRows[T any](extract func(*T) (string, bool), rows func(string, bool) ([]string, [][]string)) {
	registerRows(func(v *T) ([]string, [][]string) {
		id, deleted := extract(v)
		return rows(id, deleted)
	})
}

func registerResponseDataRows[T any](rows func([]Resource[T]) ([]string, [][]string)) {
	registerRows(func(v *Response[T]) ([]string, [][]string) {
		return rows(v.Data)
	})
}

func registerRowsWithSingleResourceAdapter[T any](rows func(*Response[T]) ([]string, [][]string)) {
	registerRows(rows)
	registerSingleResourceRowsAdapter(rows)
}

//nolint:gochecknoinits // registry init is the idiomatic way to populate a type map
func init() {
	registerRows(feedbackRows)
	registerRows(crashesRows)
	registerRows(reviewsRows)
	registerRows(customerReviewSummarizationsRows)
	registerSingleResourceRowsAdapter(reviewsRows)
	registerRows(appsRows)
	registerRows(appsWallRows)
	registerRows(appClipsRows)
	registerRows(appCategoriesRows)
	registerSingleToListRowsAdapter[AppCategoryResponse, AppCategoriesResponse](appCategoriesRows)
	registerRowsWithSingleResourceAdapter(appInfosRows)
	registerSingleResourceRowsAdapter(appsRows)
	registerSingleResourceRowsAdapter(appClipsRows)
	registerRowsWithSingleResourceAdapter(appClipDefaultExperiencesRows)
	registerRowsWithSingleResourceAdapter(appClipDefaultExperienceLocalizationsRows)
	registerRows(appClipHeaderImageRows)
	registerRows(appClipAdvancedExperienceImageRows)
	registerRowsWithSingleResourceAdapter(appClipAdvancedExperiencesRows)
	registerRows(appSetupInfoResultRows)
	registerRowsWithSingleResourceAdapter(appTagsRows)
	registerRowsWithSingleResourceAdapter(marketplaceSearchDetailsRows)
	registerRowsWithSingleResourceAdapter(marketplaceWebhooksRows)
	registerRowsWithSingleResourceAdapter(webhooksRows)
	registerRowsWithSingleResourceAdapter(webhookDeliveriesRows)
	registerRowsWithSingleResourceAdapter(alternativeDistributionDomainsRows)
	registerRowsWithSingleResourceAdapter(alternativeDistributionKeysRows)
	registerRows(alternativeDistributionPackageRows)
	registerRowsWithSingleResourceAdapter(alternativeDistributionPackageVersionsRows)
	registerRowsWithSingleResourceAdapter(alternativeDistributionPackageVariantsRows)
	registerRowsWithSingleResourceAdapter(alternativeDistributionPackageDeltasRows)
	registerRowsWithSingleResourceAdapter(backgroundAssetsRows)
	registerRowsWithSingleResourceAdapter(backgroundAssetVersionsRows)
	registerIDStateRows(func(v *BackgroundAssetVersionAppStoreReleaseResponse) (string, string) {
		return v.Data.ID, v.Data.Attributes.State
	}, backgroundAssetVersionStateRows)
	registerIDStateRows(func(v *BackgroundAssetVersionExternalBetaReleaseResponse) (string, string) {
		return v.Data.ID, v.Data.Attributes.State
	}, backgroundAssetVersionStateRows)
	registerIDStateRows(func(v *BackgroundAssetVersionInternalBetaReleaseResponse) (string, string) {
		return v.Data.ID, v.Data.Attributes.State
	}, backgroundAssetVersionStateRows)
	registerRowsWithSingleResourceAdapter(backgroundAssetUploadFilesRows)
	registerRowsWithSingleResourceAdapter(nominationsRows)
	registerRows(linkagesRows)
	registerSingleLinkageRows(func(v *AppClipDefaultExperienceReviewDetailLinkageResponse) ResourceData { return v.Data })
	registerSingleLinkageRows(func(v *AppClipDefaultExperienceReleaseWithAppStoreVersionLinkageResponse) ResourceData {
		return v.Data
	})
	registerSingleLinkageRows(func(v *AppClipDefaultExperienceLocalizationHeaderImageLinkageResponse) ResourceData {
		return v.Data
	})
	registerSingleLinkageRows(func(v *AppStoreVersionAgeRatingDeclarationLinkageResponse) ResourceData { return v.Data })
	registerSingleLinkageRows(func(v *AppStoreVersionReviewDetailLinkageResponse) ResourceData { return v.Data })
	registerSingleLinkageRows(func(v *AppStoreVersionAppClipDefaultExperienceLinkageResponse) ResourceData { return v.Data })
	registerSingleLinkageRows(func(v *AppStoreVersionSubmissionLinkageResponse) ResourceData { return v.Data })
	registerSingleLinkageRows(func(v *AppStoreVersionRoutingAppCoverageLinkageResponse) ResourceData { return v.Data })
	registerSingleLinkageRows(func(v *AppStoreVersionAlternativeDistributionPackageLinkageResponse) ResourceData {
		return v.Data
	})
	registerSingleLinkageRows(func(v *AppStoreVersionGameCenterAppVersionLinkageResponse) ResourceData { return v.Data })
	registerSingleLinkageRows(func(v *BuildAppLinkageResponse) ResourceData { return v.Data })
	registerSingleLinkageRows(func(v *BuildAppStoreVersionLinkageResponse) ResourceData { return v.Data })
	registerSingleLinkageRows(func(v *BuildBuildBetaDetailLinkageResponse) ResourceData { return v.Data })
	registerSingleLinkageRows(func(v *BuildPreReleaseVersionLinkageResponse) ResourceData { return v.Data })
	registerSingleLinkageRows(func(v *PreReleaseVersionAppLinkageResponse) ResourceData { return v.Data })
	registerSingleLinkageRows(func(v *AppInfoAgeRatingDeclarationLinkageResponse) ResourceData { return v.Data })
	registerSingleLinkageRows(func(v *AppInfoPrimaryCategoryLinkageResponse) ResourceData { return v.Data })
	registerSingleLinkageRows(func(v *AppInfoPrimarySubcategoryOneLinkageResponse) ResourceData { return v.Data })
	registerSingleLinkageRows(func(v *AppInfoPrimarySubcategoryTwoLinkageResponse) ResourceData { return v.Data })
	registerSingleLinkageRows(func(v *AppInfoSecondaryCategoryLinkageResponse) ResourceData { return v.Data })
	registerSingleLinkageRows(func(v *AppInfoSecondarySubcategoryOneLinkageResponse) ResourceData { return v.Data })
	registerSingleLinkageRows(func(v *AppInfoSecondarySubcategoryTwoLinkageResponse) ResourceData { return v.Data })
	registerRowsWithSingleResourceAdapter(bundleIDsRows)
	registerRowsWithSingleResourceAdapter(merchantIDsRows)
	registerRowsWithSingleResourceAdapter(passTypeIDsRows)
	registerRowsWithSingleResourceAdapter(certificatesRows)
	registerRowsWithSingleResourceAdapter(profilesRows)
	registerRowsWithSingleResourceAdapter(legacyInAppPurchasesRows)
	registerRowsWithSingleResourceAdapter(inAppPurchasesRows)
	registerRowsWithSingleResourceAdapter(inAppPurchaseLocalizationsRows)
	registerRowsWithSingleResourceAdapter(inAppPurchaseImagesRows)
	registerRows(inAppPurchasePricePointsRows)
	registerRowsErr(inAppPurchasePricesRows)
	registerRowsErr(inAppPurchaseOfferCodePricesRows)
	registerRowsWithSingleResourceAdapter(inAppPurchaseOfferCodesRows)
	registerRowsWithSingleResourceAdapter(inAppPurchaseOfferCodeCustomCodesRows)
	registerRowsWithSingleResourceAdapter(inAppPurchaseOfferCodeOneTimeUseCodesRows)
	registerRows(inAppPurchaseAvailabilityRows)
	registerRows(inAppPurchaseContentRows)
	registerRows(inAppPurchasePriceScheduleRows)
	registerRows(inAppPurchaseReviewScreenshotRows)
	registerRowsWithSingleResourceAdapter(appEventsRows)
	registerRowsWithSingleResourceAdapter(appEventLocalizationsRows)
	registerRowsWithSingleResourceAdapter(appEventScreenshotsRows)
	registerRowsWithSingleResourceAdapter(appEventVideoClipsRows)
	registerRowsWithSingleResourceAdapter(subscriptionGroupsRows)
	registerRowsWithSingleResourceAdapter(subscriptionsRows)
	registerRowsWithSingleResourceAdapter(promotedPurchasesRows)
	registerRowsErr(subscriptionPricesRows)
	registerRows(subscriptionPriceRows)
	registerRows(subscriptionAvailabilityRows)
	registerRows(subscriptionGracePeriodRows)
	registerRowsWithSingleResourceAdapter(territoriesRows)
	registerRowsErr(territoryAgeRatingsRows)
	registerRows(offerCodeValuesRows)
	registerRows(appPricePointsRows)
	registerRows(appPriceScheduleRows)
	registerRows(appPricesRows)
	registerRows(buildsRows)
	registerRows(buildBundlesRows)
	registerRows(buildBundleFileSizesRows)
	registerRows(betaAppClipInvocationsRows)
	registerSingleResourceRowsAdapter(betaAppClipInvocationsRows)
	registerRows(betaAppClipInvocationLocalizationsRows)
	registerSingleResourceRowsAdapter(betaAppClipInvocationLocalizationsRows)
	registerRows(offerCodesRows)
	registerRows(offerCodeCustomCodesRows)
	registerRows(subscriptionOfferCodeRows)
	registerRows(winBackOffersRows)
	registerSingleResourceRowsAdapter(winBackOffersRows)
	registerRowsErr(winBackOfferPricesRows)
	registerRows(appStoreVersionsRows)
	registerSingleResourceRowsAdapter(appStoreVersionsRows)
	registerRows(preReleaseVersionsRows)
	registerSingleResourceRowsAdapter(buildsRows)
	registerRows(buildIconsRows)
	registerRows(buildUploadsRows)
	registerRows(buildsLatestNextRows)
	registerSingleResourceRowsAdapter(buildUploadsRows)
	registerRows(buildUploadFilesRows)
	registerSingleResourceRowsAdapter(buildUploadFilesRows)
	registerDirect(func(v *AppClipDomainStatusResult, render func([]string, [][]string)) error {
		h, r := appClipDomainStatusMainRows(v)
		render(h, r)
		if len(v.Domains) > 0 {
			dh, dr := appClipDomainStatusDomainRows(v)
			render(dh, dr)
		}
		return nil
	})
	registerSingleToListRowsAdapter[SubscriptionOfferCodeOneTimeUseCodeResponse, SubscriptionOfferCodeOneTimeUseCodesResponse](offerCodesRows)
	registerSingleToListRowsAdapter[SubscriptionOfferCodeCustomCodeResponse, SubscriptionOfferCodeCustomCodesResponse](offerCodeCustomCodesRows)
	registerRows(winBackOfferDeleteResultRows)
	registerRows(subscriptionPriceDeleteResultRows)
	registerRowsErr(offerCodePricesRows)
	registerRows(appAvailabilityRows)
	registerRows(territoryAvailabilitiesRows)
	registerRows(endAppAvailabilityPreOrderRows)
	registerSingleToListRowsAdapter[PreReleaseVersionResponse, PreReleaseVersionsResponse](preReleaseVersionsRows)
	registerRows(appStoreVersionLocalizationsRows)
	registerSingleResourceRowsAdapter(appStoreVersionLocalizationsRows)
	registerRows(betaAppLocalizationsRows)
	registerSingleResourceRowsAdapter(betaAppLocalizationsRows)
	registerRows(betaBuildLocalizationsRows)
	registerSingleResourceRowsAdapter(betaBuildLocalizationsRows)
	registerRows(appInfoLocalizationsRows)
	registerRows(appScreenshotSetsRows)
	registerSingleResourceRowsAdapter(appScreenshotSetsRows)
	registerRows(appScreenshotsRows)
	registerSingleResourceRowsAdapter(appScreenshotsRows)
	registerRows(appPreviewSetsRows)
	registerSingleResourceRowsAdapter(appPreviewSetsRows)
	registerRows(appPreviewsRows)
	registerSingleResourceRowsAdapter(appPreviewsRows)
	registerRows(betaGroupsRows)
	registerSingleResourceRowsAdapter(betaGroupsRows)
	registerRows(betaTestersRows)
	registerSingleResourceRowsAdapter(betaTestersRows)
	registerRows(usersRows)
	registerSingleResourceRowsAdapter(usersRows)
	registerRows(actorsRows)
	registerSingleResourceRowsAdapter(actorsRows)
	registerRows(devicesRows)
	registerRows(deviceLocalUDIDRows)
	registerSingleResourceRowsAdapter(devicesRows)
	registerRows(userInvitationsRows)
	registerSingleResourceRowsAdapter(userInvitationsRows)
	registerRows(userDeleteResultRows)
	registerRows(userInvitationRevokeResultRows)
	registerRows(betaAppReviewDetailsRows)
	registerSingleResourceRowsAdapter(betaAppReviewDetailsRows)
	registerRows(betaAppReviewSubmissionsRows)
	registerSingleResourceRowsAdapter(betaAppReviewSubmissionsRows)
	registerRows(buildBetaDetailsRows)
	registerSingleResourceRowsAdapter(buildBetaDetailsRows)
	registerRows(betaLicenseAgreementsRows)
	registerSingleToListRowsAdapter[BetaLicenseAgreementResponse, BetaLicenseAgreementsResponse](betaLicenseAgreementsRows)
	registerRows(buildBetaNotificationRows)
	registerRows(ageRatingDeclarationRows)
	registerRows(accessibilityDeclarationsRows)
	registerRows(accessibilityDeclarationRows)
	registerRows(appStoreReviewDetailRows)
	registerRows(appStoreReviewAttachmentsRows)
	registerRows(appStoreReviewAttachmentRows)
	registerRows(appClipAppStoreReviewDetailRows)
	registerRows(routingAppCoverageRows)
	registerRows(appEncryptionDeclarationsRows)
	registerRows(appEncryptionDeclarationRows)
	registerRows(appEncryptionDeclarationDocumentRows)
	registerRows(betaRecruitmentCriterionOptionsRows)
	registerRows(betaRecruitmentCriteriaRows)
	registerRows(betaRecruitmentCriteriaDeleteResultRows)
	registerResponseDataRows(betaGroupMetricsRows)
	registerRows(sandboxTestersRows)
	registerSingleResourceRowsAdapter(sandboxTestersRows)
	registerRows(bundleIDCapabilitiesRows)
	registerSingleResourceRowsAdapter(bundleIDCapabilitiesRows)
	registerRows(localizationDownloadResultRows)
	registerRows(localizationUploadResultRows)
	registerDirect(func(v *BuildUploadResult, render func([]string, [][]string)) error {
		h, r := buildUploadResultRows(v)
		render(h, r)
		if len(v.Operations) > 0 {
			oh, or := buildUploadOperationsRows(v.Operations)
			render(oh, or)
		}
		return nil
	})
	registerRows(buildExpireAllResultRows)
	registerRows(appScreenshotListResultRows)
	registerRows(screenshotSizesRows)
	registerRows(appPreviewListResultRows)
	registerDirect(func(v *AppScreenshotUploadResult, render func([]string, [][]string)) error {
		h, r := appScreenshotUploadResultMainRows(v)
		render(h, r)
		if len(v.Results) > 0 {
			ih, ir := assetUploadResultItemRows(v.Results)
			render(ih, ir)
		}
		return nil
	})
	registerDirect(func(v *AppPreviewUploadResult, render func([]string, [][]string)) error {
		h, r := appPreviewUploadResultMainRows(v)
		render(h, r)
		if len(v.Results) > 0 {
			ih, ir := assetUploadResultItemRows(v.Results)
			render(ih, ir)
		}
		return nil
	})
	registerRows(appClipAdvancedExperienceImageUploadResultRows)
	registerRows(appClipHeaderImageUploadResultRows)
	registerRows(assetDeleteResultRows)
	registerRows(appClipDefaultExperienceDeleteResultRows)
	registerRows(appClipDefaultExperienceLocalizationDeleteResultRows)
	registerRows(appClipAdvancedExperienceDeleteResultRows)
	registerRows(appClipAdvancedExperienceImageDeleteResultRows)
	registerRows(appClipHeaderImageDeleteResultRows)
	registerRows(betaAppClipInvocationDeleteResultRows)
	registerRows(betaAppClipInvocationLocalizationDeleteResultRows)
	registerRows(testFlightPublishResultRows)
	registerRows(appStorePublishResultRows)
	registerRows(salesReportResultRows)
	registerRows(financeReportResultRows)
	registerRows(financeRegionsRows)
	registerRows(analyticsReportRequestResultRows)
	registerRows(analyticsReportRequestDeleteResultRows)
	registerRows(analyticsReportRequestsRows)
	registerSingleToListRowsAdapter[AnalyticsReportRequestResponse, AnalyticsReportRequestsResponse](analyticsReportRequestsRows)
	registerRows(analyticsReportDownloadResultRows)
	registerRows(analyticsReportGetResultRows)
	registerRows(analyticsReportsRows)
	registerSingleToListRowsAdapter[AnalyticsReportResponse, AnalyticsReportsResponse](analyticsReportsRows)
	registerRows(analyticsReportInstancesRows)
	registerSingleToListRowsAdapter[AnalyticsReportInstanceResponse, AnalyticsReportInstancesResponse](analyticsReportInstancesRows)
	registerRows(analyticsReportSegmentsRows)
	registerSingleToListRowsAdapter[AnalyticsReportSegmentResponse, AnalyticsReportSegmentsResponse](analyticsReportSegmentsRows)
	registerRows(appStoreVersionSubmissionRows)
	registerRows(appStoreVersionSubmissionCreateRows)
	registerRows(appStoreVersionSubmissionStatusRows)
	registerRows(appStoreVersionSubmissionCancelRows)
	registerRows(appStoreVersionDetailRows)
	registerRows(appStoreVersionAttachBuildRows)
	registerRows(reviewSubmissionsRows)
	registerSingleToListRowsAdapter[ReviewSubmissionResponse, ReviewSubmissionsResponse](reviewSubmissionsRows)
	registerRows(reviewSubmissionItemsRows)
	registerSingleToListRowsAdapter[ReviewSubmissionItemResponse, ReviewSubmissionItemsResponse](reviewSubmissionItemsRows)
	registerRows(reviewSubmissionItemDeleteResultRows)
	registerRows(appStoreVersionReleaseRequestRows)
	registerRows(appStoreVersionPromotionCreateRows)
	registerRows(appStoreVersionPhasedReleaseRows)
	registerRows(appStoreVersionPhasedReleaseDeleteResultRows)
	registerRows(buildBetaGroupsUpdateRows)
	registerRows(buildIndividualTestersUpdateRows)
	registerRows(buildUploadDeleteResultRows)
	registerRows(inAppPurchaseDeleteResultRows)
	registerRows(appEventDeleteResultRows)
	registerRows(appEventLocalizationDeleteResultRows)
	registerRows(appEventSubmissionResultRows)
	registerRows(gameCenterAchievementsRows)
	registerSingleResourceRowsAdapter(gameCenterAchievementsRows)
	registerRows(gameCenterAchievementDeleteResultRows)
	registerRows(gameCenterAchievementVersionsRows)
	registerSingleResourceRowsAdapter(gameCenterAchievementVersionsRows)
	registerRows(gameCenterLeaderboardsRows)
	registerSingleResourceRowsAdapter(gameCenterLeaderboardsRows)
	registerRows(gameCenterLeaderboardDeleteResultRows)
	registerRows(gameCenterLeaderboardVersionsRows)
	registerSingleResourceRowsAdapter(gameCenterLeaderboardVersionsRows)
	registerRows(gameCenterLeaderboardSetsRows)
	registerSingleResourceRowsAdapter(gameCenterLeaderboardSetsRows)
	registerRows(gameCenterLeaderboardSetDeleteResultRows)
	registerRows(gameCenterLeaderboardSetVersionsRows)
	registerSingleResourceRowsAdapter(gameCenterLeaderboardSetVersionsRows)
	registerRows(gameCenterLeaderboardLocalizationsRows)
	registerSingleResourceRowsAdapter(gameCenterLeaderboardLocalizationsRows)
	registerRows(gameCenterLeaderboardLocalizationDeleteResultRows)
	registerRows(gameCenterLeaderboardReleasesRows)
	registerSingleResourceRowsAdapter(gameCenterLeaderboardReleasesRows)
	registerRows(gameCenterLeaderboardReleaseDeleteResultRows)
	registerRows(gameCenterLeaderboardEntrySubmissionRows)
	registerRows(gameCenterPlayerAchievementSubmissionRows)
	registerRows(gameCenterLeaderboardSetReleasesRows)
	registerSingleResourceRowsAdapter(gameCenterLeaderboardSetReleasesRows)
	registerRows(gameCenterLeaderboardSetReleaseDeleteResultRows)
	registerRows(gameCenterLeaderboardSetLocalizationsRows)
	registerSingleResourceRowsAdapter(gameCenterLeaderboardSetLocalizationsRows)
	registerRows(gameCenterLeaderboardSetLocalizationDeleteResultRows)
	registerRows(gameCenterAchievementReleasesRows)
	registerSingleResourceRowsAdapter(gameCenterAchievementReleasesRows)
	registerRows(gameCenterAchievementReleaseDeleteResultRows)
	registerRows(gameCenterAchievementLocalizationsRows)
	registerSingleResourceRowsAdapter(gameCenterAchievementLocalizationsRows)
	registerRows(gameCenterAchievementLocalizationDeleteResultRows)
	registerRows(gameCenterLeaderboardImageUploadResultRows)
	registerRows(gameCenterLeaderboardImageDeleteResultRows)
	registerRows(gameCenterAchievementImageUploadResultRows)
	registerRows(gameCenterAchievementImageDeleteResultRows)
	registerRows(gameCenterLeaderboardSetImageUploadResultRows)
	registerRows(gameCenterLeaderboardSetImageDeleteResultRows)
	registerRows(gameCenterChallengesRows)
	registerSingleResourceRowsAdapter(gameCenterChallengesRows)
	registerRows(gameCenterChallengeDeleteResultRows)
	registerRows(gameCenterChallengeVersionsRows)
	registerSingleResourceRowsAdapter(gameCenterChallengeVersionsRows)
	registerRows(gameCenterChallengeLocalizationsRows)
	registerSingleResourceRowsAdapter(gameCenterChallengeLocalizationsRows)
	registerRows(gameCenterChallengeLocalizationDeleteResultRows)
	registerRows(gameCenterChallengeImagesRows)
	registerSingleResourceRowsAdapter(gameCenterChallengeImagesRows)
	registerRows(gameCenterChallengeImageUploadResultRows)
	registerRows(gameCenterChallengeImageDeleteResultRows)
	registerRows(gameCenterChallengeReleasesRows)
	registerSingleResourceRowsAdapter(gameCenterChallengeReleasesRows)
	registerRows(gameCenterChallengeReleaseDeleteResultRows)
	registerRows(gameCenterActivitiesRows)
	registerSingleResourceRowsAdapter(gameCenterActivitiesRows)
	registerRows(gameCenterActivityDeleteResultRows)
	registerRows(gameCenterActivityVersionsRows)
	registerSingleResourceRowsAdapter(gameCenterActivityVersionsRows)
	registerRows(gameCenterActivityLocalizationsRows)
	registerSingleResourceRowsAdapter(gameCenterActivityLocalizationsRows)
	registerRows(gameCenterActivityLocalizationDeleteResultRows)
	registerRows(gameCenterActivityImagesRows)
	registerSingleResourceRowsAdapter(gameCenterActivityImagesRows)
	registerRows(gameCenterActivityImageUploadResultRows)
	registerRows(gameCenterActivityImageDeleteResultRows)
	registerRows(gameCenterActivityReleasesRows)
	registerSingleResourceRowsAdapter(gameCenterActivityReleasesRows)
	registerRows(gameCenterActivityReleaseDeleteResultRows)
	registerRows(gameCenterGroupsRows)
	registerSingleResourceRowsAdapter(gameCenterGroupsRows)
	registerRows(gameCenterGroupDeleteResultRows)
	registerRows(gameCenterAppVersionsRows)
	registerSingleResourceRowsAdapter(gameCenterAppVersionsRows)
	registerRows(gameCenterEnabledVersionsRows)
	registerRows(gameCenterDetailsRows)
	registerSingleResourceRowsAdapter(gameCenterDetailsRows)
	registerRows(gameCenterMatchmakingQueuesRows)
	registerSingleResourceRowsAdapter(gameCenterMatchmakingQueuesRows)
	registerRows(gameCenterMatchmakingQueueDeleteResultRows)
	registerRows(gameCenterMatchmakingRuleSetsRows)
	registerSingleResourceRowsAdapter(gameCenterMatchmakingRuleSetsRows)
	registerRows(gameCenterMatchmakingRuleSetDeleteResultRows)
	registerRows(gameCenterMatchmakingRulesRows)
	registerSingleResourceRowsAdapter(gameCenterMatchmakingRulesRows)
	registerRows(gameCenterMatchmakingRuleDeleteResultRows)
	registerRows(gameCenterMatchmakingTeamsRows)
	registerSingleResourceRowsAdapter(gameCenterMatchmakingTeamsRows)
	registerRows(gameCenterMatchmakingTeamDeleteResultRows)
	registerRows(gameCenterMetricsRows)
	registerRows(gameCenterMatchmakingRuleSetTestRows)
	registerRows(subscriptionGroupDeleteResultRows)
	registerRows(subscriptionDeleteResultRows)
	registerRows(betaTesterDeleteResultRows)
	registerRows(betaTesterGroupsUpdateResultRows)
	registerRows(betaTesterAppsUpdateResultRows)
	registerRows(betaTesterBuildsUpdateResultRows)
	registerRows(appBetaTestersUpdateResultRows)
	registerRows(betaFeedbackSubmissionDeleteResultRows)
	registerRows(appStoreVersionLocalizationDeleteResultRows)
	registerRows(betaAppLocalizationDeleteResultRows)
	registerRows(betaBuildLocalizationDeleteResultRows)
	registerRows(betaTesterInvitationResultRows)
	registerRows(promotedPurchaseDeleteResultRows)
	registerRows(appPromotedPurchasesLinkResultRows)
	registerRows(sandboxTesterClearHistoryResultRows)
	registerRows(bundleIDDeleteResultRows)
	registerRows(marketplaceSearchDetailDeleteResultRows)
	registerRows(marketplaceWebhookDeleteResultRows)
	registerRows(webhookDeleteResultRows)
	registerRows(webhookPingRows)
	registerRows(merchantIDDeleteResultRows)
	registerRows(passTypeIDDeleteResultRows)
	registerRows(bundleIDCapabilityDeleteResultRows)
	registerRows(certificateRevokeResultRows)
	registerRows(profileDeleteResultRows)
	registerRows(endUserLicenseAgreementRows)
	registerRows(endUserLicenseAgreementDeleteResultRows)
	registerRows(profileDownloadResultRows)
	registerRows(signingFetchResultRows)
	registerRows(xcodeCloudRunResultRows)
	registerRows(xcodeCloudStatusResultRows)
	registerRows(ciProductsRows)
	registerSingleToListRowsAdapter[CiProductResponse, CiProductsResponse](ciProductsRows)
	registerRows(ciWorkflowsRows)
	registerSingleToListRowsAdapter[CiWorkflowResponse, CiWorkflowsResponse](ciWorkflowsRows)
	registerRows(scmProvidersRows)
	registerSingleToListRowsAdapter[ScmProviderResponse, ScmProvidersResponse](scmProvidersRows)
	registerRows(scmRepositoriesRows)
	registerRows(scmGitReferencesRows)
	registerSingleToListRowsAdapter[ScmGitReferenceResponse, ScmGitReferencesResponse](scmGitReferencesRows)
	registerRows(scmPullRequestsRows)
	registerSingleToListRowsAdapter[ScmPullRequestResponse, ScmPullRequestsResponse](scmPullRequestsRows)
	registerRows(ciBuildRunsRows)
	registerSingleToListRowsAdapter[CiBuildRunResponse, CiBuildRunsResponse](ciBuildRunsRows)
	registerRows(ciBuildActionsRows)
	registerSingleToListRowsAdapter[CiBuildActionResponse, CiBuildActionsResponse](ciBuildActionsRows)
	registerRows(ciMacOsVersionsRows)
	registerSingleToListRowsAdapter[CiMacOsVersionResponse, CiMacOsVersionsResponse](ciMacOsVersionsRows)
	registerRows(ciXcodeVersionsRows)
	registerSingleToListRowsAdapter[CiXcodeVersionResponse, CiXcodeVersionsResponse](ciXcodeVersionsRows)
	registerRows(ciArtifactsRows)
	registerSingleToListRowsAdapter[CiArtifactResponse, CiArtifactsResponse](ciArtifactsRows)
	registerRows(ciTestResultsRows)
	registerSingleToListRowsAdapter[CiTestResultResponse, CiTestResultsResponse](ciTestResultsRows)
	registerRows(ciIssuesRows)
	registerSingleToListRowsAdapter[CiIssueResponse, CiIssuesResponse](ciIssuesRows)
	registerRows(ciArtifactDownloadResultRows)
	registerRows(ciWorkflowDeleteResultRows)
	registerRows(ciProductDeleteResultRows)
	registerRows(customerReviewResponseRows)
	registerRows(customerReviewResponseDeleteResultRows)
	registerRows(accessibilityDeclarationDeleteResultRows)
	registerRows(appStoreReviewAttachmentDeleteResultRows)
	registerRows(routingAppCoverageDeleteResultRows)
	registerRows(nominationDeleteResultRows)
	registerRows(appEncryptionDeclarationBuildsUpdateResultRows)
	registerRows(androidToIosAppMappingDetailsRows)
	registerSingleResourceRowsAdapter(androidToIosAppMappingDetailsRows)
	registerRows(androidToIosAppMappingDeleteResultRows)
	registerIDBoolRows(func(v *AlternativeDistributionDomainDeleteResult) (string, bool) {
		return v.ID, v.Deleted
	}, alternativeDistributionDeleteResultRows)
	registerIDBoolRows(func(v *AlternativeDistributionKeyDeleteResult) (string, bool) {
		return v.ID, v.Deleted
	}, alternativeDistributionDeleteResultRows)
	registerRows(appCustomProductPagesRows)
	registerSingleResourceRowsAdapter(appCustomProductPagesRows)
	registerRows(appCustomProductPageVersionsRows)
	registerSingleResourceRowsAdapter(appCustomProductPageVersionsRows)
	registerRows(appCustomProductPageLocalizationsRows)
	registerSingleResourceRowsAdapter(appCustomProductPageLocalizationsRows)
	registerRows(appKeywordsRows)
	registerRows(appStoreVersionExperimentsRows)
	registerSingleResourceRowsAdapter(appStoreVersionExperimentsRows)
	registerRows(appStoreVersionExperimentsV2Rows)
	registerSingleResourceRowsAdapter(appStoreVersionExperimentsV2Rows)
	registerRows(appStoreVersionExperimentTreatmentsRows)
	registerSingleResourceRowsAdapter(appStoreVersionExperimentTreatmentsRows)
	registerRows(appStoreVersionExperimentTreatmentLocalizationsRows)
	registerSingleResourceRowsAdapter(appStoreVersionExperimentTreatmentLocalizationsRows)
	registerRows(appCustomProductPageDeleteResultRows)
	registerRows(appCustomProductPageLocalizationDeleteResultRows)
	registerRows(appStoreVersionExperimentDeleteResultRows)
	registerRows(appStoreVersionExperimentTreatmentDeleteResultRows)
	registerRows(appStoreVersionExperimentTreatmentLocalizationDeleteResultRows)
	registerRowsErr(perfPowerMetricsRows)
	registerRows(diagnosticSignaturesRows)
	registerRowsErr(diagnosticLogsRows)
	registerRows(performanceDownloadResultRows)
	registerRows(notarySubmissionStatusRows)
	registerRows(notarySubmissionsListRows)
	registerRows(notarySubmissionLogsRows)
}
